const movies = [
  {
    id: 1,
    title: "Better Man 2024 | download hollywood movie",
    date: "February 2, 2024",
    image: "https://via.placeholder.com/150?text=Better+Man+2024",
    slug: "better-man-2024",
    downloadLink: "https://doodstream.com/dl/better-man-2024-download",
  },
  {
    id: 2,
    title: "Deadpool 3 | download hollywood movie",
    date: "March 15, 2024",
    image: "https://via.placeholder.com/150?text=Deadpool+3",
    slug: "deadpool-3",
    downloadLink: "https://streamtape.com/v/deadpool-3-hollywood-movie",
  },
  {
    id: 3,
    title: "Fast & Furious 10 | download hollywood movie",
    date: "April 10, 2024",
    image: "https://via.placeholder.com/150?text=Fast+%26+Furious+10",
    slug: "fast-and-furious-10",
    downloadLink: "https://mixdrop.co/e/fast-and-furious-10-full-movie",
  },
  {
    id: 4,
    title: "Aquaman 2 | download hollywood movie",
    date: "December 20, 2023",
    image: "https://via.placeholder.com/150?text=Aquaman+2",
    slug: "aquaman-2",
    downloadLink: "https://filemoon.sx/dl/aquaman-2-2023-download",
  },
  {
    id: 5,
    title: "Mission Impossible 8",
    date: "July 15, 2024",
    image: "https://via.placeholder.com/150?text=Mission+Impossible+8",
    slug: "mission-impossible-8",
    downloadLink: "https://doodstream.com/dl/mission-impossible-8",
  },
  {
    id: 6,
    title: "Avatar 3 | download hollywood movie",
    date: "December 18, 2025",
    image: "https://via.placeholder.com/150?text=Avatar+3",
    slug: "avatar-3",
    downloadLink: "https://streamhub.to/watch/avatar-3-download",
  },
  {
    id: 7,
    title: "Black Panther: Wakanda Forever | download hollywood movie",
    date: "November 11, 2022",
    image: "https://via.placeholder.com/150?text=Black+Panther",
    slug: "black-panther-wakanda-forever",
    downloadLink: "https://videozoo.cc/file/black-panther-wakanda-forever",
  },
  {
    id: 8,
    title: "The Batman | download hollywood movie",
    date: "March 4, 2022",
    image: "https://via.placeholder.com/150?text=The+Batman",
    slug: "the-batman",
    downloadLink: "https://filesharer.io/dl/the-batman-2022",
  },
  {
    id: 9,
    title: "Spider-Man: No Way Home | download hollywood movie",
    date: "December 17, 2021",
    image: "https://via.placeholder.com/150?text=Spider-Man+No+Way+Home",
    slug: "spider-man-no-way-home",
    downloadLink: "https://vidstream.xyz/watch/spider-man-no-way-home",
  },
  {
    id: 10,
    title: "The Flash | download hollywood movie",
    date: "June 16, 2023",
    image: "https://via.placeholder.com/150?text=The+Flash",
    slug: "the-flash-2023",
    downloadLink: "https://downloadfy.net/movie/the-flash-2023",
  },
];

export default movies;
